# Generated by Django 4.1.5 on 2023-02-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='notes.tags'),
        ),
    ]
