# Generated by Django 4.1.5 on 2023-02-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_updated_at_alter_notes_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='created',
            new_name='created_at',
        ),
    ]
